package com.leon1236.reforestry.arboriculture.client;

import java.util.Map;

import com.google.common.collect.ImmutableMap;

import net.fabricmc.fabric.api.client.model.loading.v1.BlockStateResolver;

import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.state.BlockState;

import com.leon1236.reforestry.ReForestry;

/**
 * Block-level per-species dispatch for the sapling_ge block, mirroring LeafBlockStateResolver.
 * No overlay, no pollinated variant, no tint (sapling art is already full-color per species,
 * unlike the grayscale leaf textures).
 *
 * <p>Table generated by tools/generate_sapling_block_models.py, which also copies the 43
 * non-vanilla-wood species' textures into the block atlas and writes their block models; the 7
 * vanilla-wood species reuse vanilla's own sapling block models directly.
 */
public final class SaplingBlockStateResolver implements BlockStateResolver {
    private static final Map<String, String> SPECIES_TO_MODEL = Map.ofEntries(
            Map.entry("acacia", "minecraft:block/acacia_sapling"),
            Map.entry("balsa", "reforestry:block/tree_saplings/balsa"),
            Map.entry("baobab", "reforestry:block/tree_saplings/baobab"),
            Map.entry("beech", "reforestry:block/tree_saplings/beech"),
            Map.entry("birch", "minecraft:block/birch_sapling"),
            Map.entry("cherry", "minecraft:block/cherry_sapling"),
            Map.entry("chestnut", "reforestry:block/tree_saplings/chestnut"),
            Map.entry("cocobolo", "reforestry:block/tree_saplings/cocobolo"),
            Map.entry("coconut", "reforestry:block/tree_saplings/coconut"),
            Map.entry("dark_oak", "minecraft:block/dark_oak_sapling"),
            Map.entry("date", "reforestry:block/tree_saplings/date"),
            Map.entry("desert_acacia", "reforestry:block/tree_saplings/desert_acacia"),
            Map.entry("dogwood", "reforestry:block/tree_saplings/dogwood"),
            Map.entry("ebony", "reforestry:block/tree_saplings/ebony"),
            Map.entry("elm", "reforestry:block/tree_saplings/elm"),
            Map.entry("feijoa", "reforestry:block/tree_saplings/feijoa"),
            Map.entry("fir", "reforestry:block/tree_saplings/fir"),
            Map.entry("giant_sequoia", "reforestry:block/tree_saplings/giant_sequoia"),
            Map.entry("ginkgo", "reforestry:block/tree_saplings/ginkgo"),
            Map.entry("hill_cherry", "reforestry:block/tree_saplings/hill_cherry"),
            Map.entry("ipe", "reforestry:block/tree_saplings/ipe"),
            Map.entry("jacaranda", "reforestry:block/tree_saplings/jacaranda"),
            Map.entry("jungle", "minecraft:block/jungle_sapling"),
            Map.entry("kapok", "reforestry:block/tree_saplings/kapok"),
            Map.entry("kauri", "reforestry:block/tree_saplings/kauri"),
            Map.entry("larch", "reforestry:block/tree_saplings/larch"),
            Map.entry("lemon", "reforestry:block/tree_saplings/lemon"),
            Map.entry("lime", "reforestry:block/tree_saplings/lime"),
            Map.entry("macrocarpa", "reforestry:block/tree_saplings/macrocarpa"),
            Map.entry("mahoe", "reforestry:block/tree_saplings/mahoe"),
            Map.entry("mahogany", "reforestry:block/tree_saplings/mahogany"),
            Map.entry("maple", "reforestry:block/tree_saplings/maple"),
            Map.entry("oak", "minecraft:block/oak_sapling"),
            Map.entry("olive", "reforestry:block/tree_saplings/olive"),
            Map.entry("orange", "reforestry:block/tree_saplings/orange"),
            Map.entry("padauk", "reforestry:block/tree_saplings/padauk"),
            Map.entry("papaya", "reforestry:block/tree_saplings/papaya"),
            Map.entry("pear", "reforestry:block/tree_saplings/pear"),
            Map.entry("pewen", "reforestry:block/tree_saplings/pewen"),
            Map.entry("pine", "reforestry:block/tree_saplings/pine"),
            Map.entry("plum", "reforestry:block/tree_saplings/plum"),
            Map.entry("poplar", "reforestry:block/tree_saplings/poplar"),
            Map.entry("sequoia", "reforestry:block/tree_saplings/sequoia"),
            Map.entry("sipiri", "reforestry:block/tree_saplings/sipiri"),
            Map.entry("spruce", "minecraft:block/spruce_sapling"),
            Map.entry("teak", "reforestry:block/tree_saplings/teak"),
            Map.entry("walnut", "reforestry:block/tree_saplings/walnut"),
            Map.entry("wenge", "reforestry:block/tree_saplings/wenge"),
            Map.entry("willow", "reforestry:block/tree_saplings/willow"),
            Map.entry("zebrawood", "reforestry:block/tree_saplings/zebrawood")
    );

    private static final String FALLBACK_SPECIES = "oak";

    @Override
    public void resolveBlockStates(Context context) {
        ImmutableMap.Builder<Identifier, Identifier> base = ImmutableMap.builder();
        for (Map.Entry<String, String> entry : SPECIES_TO_MODEL.entrySet()) {
            base.put(ReForestry.id("tree_" + entry.getKey()), Identifier.parse(entry.getValue()));
        }
        Identifier fallback = Identifier.parse(SPECIES_TO_MODEL.get(FALLBACK_SPECIES));

        SpeciesDispatchModel.Unbaked model = new SpeciesDispatchModel.Unbaked(base.build(), Map.of(), fallback, null);
        for (BlockState state : context.block().getStateDefinition().getPossibleStates()) {
            context.setModel(state, model);
        }
    }
}
