package com.leon1236.reforestry.arboriculture.client;

import java.util.Map;

import com.google.common.collect.ImmutableMap;

import net.fabricmc.fabric.api.client.model.loading.v1.BlockStateResolver;

import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.state.BlockState;

import com.leon1236.reforestry.ReForestry;

/**
 * Block-level per-species dispatch for the sapling_ge block, mirroring LeafBlockStateResolver.
 * No overlay, no pollinated variant, no tint (sapling art is already full-color per species,
 * unlike the grayscale leaf textures).
 *
 * <p>Table generated by tools/generate_sapling_block_models.py, which also copies the 43
 * non-vanilla-wood species' textures into the block atlas and writes their block models; the 7
 * vanilla-wood species reuse vanilla's own sapling block models directly.
 */
public final class SaplingBlockStateResolver implements BlockStateResolver {
    private static final Map<String, String> SPECIES_TO_MODEL = Map.ofEntries(
            Map.entry("acacia", "minecraft:block/acacia_sapling"),
            Map.entry("acorn_oak", "reforestry:block/tree_saplings/acorn_oak"),
            Map.entry("alder", "reforestry:block/tree_saplings/alder"),
            Map.entry("allspice", "reforestry:block/tree_saplings/allspice"),
            Map.entry("almond", "reforestry:block/tree_saplings/almond"),
            Map.entry("apricot", "reforestry:block/tree_saplings/apricot"),
            Map.entry("ash", "reforestry:block/tree_saplings/ash"),
            Map.entry("aspen", "reforestry:block/tree_saplings/aspen"),
            Map.entry("avocado", "reforestry:block/tree_saplings/avocado"),
            Map.entry("balsa", "reforestry:block/tree_saplings/balsa"),
            Map.entry("banana", "reforestry:block/tree_saplings/banana"),
            Map.entry("baobab", "reforestry:block/tree_saplings/baobab"),
            Map.entry("beech", "reforestry:block/tree_saplings/beech"),
            Map.entry("birch", "minecraft:block/birch_sapling"),
            Map.entry("black_cherry", "reforestry:block/tree_saplings/black_cherry"),
            Map.entry("blackberry", "reforestry:block/tree_saplings/blackberry"),
            Map.entry("blackcurrant", "reforestry:block/tree_saplings/blackcurrant"),
            Map.entry("blackthorn", "reforestry:block/tree_saplings/blackthorn"),
            Map.entry("blueberry", "reforestry:block/tree_saplings/blueberry"),
            Map.entry("box", "reforestry:block/tree_saplings/box"),
            Map.entry("brazilnut", "reforestry:block/tree_saplings/brazilnut"),
            Map.entry("brazilwood", "reforestry:block/tree_saplings/brazilwood"),
            Map.entry("buddha_hand", "reforestry:block/tree_saplings/buddha_hand"),
            Map.entry("butternut", "reforestry:block/tree_saplings/butternut"),
            Map.entry("candlenut", "reforestry:block/tree_saplings/candlenut"),
            Map.entry("cashew", "reforestry:block/tree_saplings/cashew"),
            Map.entry("cedar", "reforestry:block/tree_saplings/cedar"),
            Map.entry("cherry", "minecraft:block/cherry_sapling"),
            Map.entry("cherry_plum", "reforestry:block/tree_saplings/cherry_plum"),
            Map.entry("chestnut", "reforestry:block/tree_saplings/chestnut"),
            Map.entry("chilli", "reforestry:block/tree_saplings/chilli"),
            Map.entry("cinnamon", "reforestry:block/tree_saplings/cinnamon"),
            Map.entry("citron", "reforestry:block/tree_saplings/citron"),
            Map.entry("clove", "reforestry:block/tree_saplings/clove"),
            Map.entry("cocobolo", "reforestry:block/tree_saplings/cocobolo"),
            Map.entry("coconut", "reforestry:block/tree_saplings/coconut"),
            Map.entry("coffee", "reforestry:block/tree_saplings/coffee"),
            Map.entry("copper_beech", "reforestry:block/tree_saplings/copper_beech"),
            Map.entry("cranberry", "reforestry:block/tree_saplings/cranberry"),
            Map.entry("cypress", "reforestry:block/tree_saplings/cypress"),
            Map.entry("dark_oak", "minecraft:block/dark_oak_sapling"),
            Map.entry("date", "reforestry:block/tree_saplings/date"),
            Map.entry("desert_acacia", "reforestry:block/tree_saplings/desert_acacia"),
            Map.entry("dogwood", "reforestry:block/tree_saplings/dogwood"),
            Map.entry("douglas_fir", "reforestry:block/tree_saplings/douglas_fir"),
            Map.entry("dwarf_hazel", "reforestry:block/tree_saplings/dwarf_hazel"),
            Map.entry("ebony", "reforestry:block/tree_saplings/ebony"),
            Map.entry("elder", "reforestry:block/tree_saplings/elder"),
            Map.entry("elm", "reforestry:block/tree_saplings/elm"),
            Map.entry("et_elm", "reforestry:block/tree_saplings/et_elm"),
            Map.entry("et_fir", "reforestry:block/tree_saplings/et_fir"),
            Map.entry("et_lime", "reforestry:block/tree_saplings/et_lime"),
            Map.entry("feijoa", "reforestry:block/tree_saplings/feijoa"),
            Map.entry("finger_lime", "reforestry:block/tree_saplings/finger_lime"),
            Map.entry("fir", "reforestry:block/tree_saplings/fir"),
            Map.entry("flowering_crabapple", "reforestry:block/tree_saplings/flowering_crabapple"),
            Map.entry("giant_sequoia", "reforestry:block/tree_saplings/giant_sequoia"),
            Map.entry("ginkgo", "reforestry:block/tree_saplings/ginkgo"),
            Map.entry("golden_raspberry", "reforestry:block/tree_saplings/golden_raspberry"),
            Map.entry("gooseberry", "reforestry:block/tree_saplings/gooseberry"),
            Map.entry("grapefruit", "reforestry:block/tree_saplings/grapefruit"),
            Map.entry("hawthorn", "reforestry:block/tree_saplings/hawthorn"),
            Map.entry("hazel", "reforestry:block/tree_saplings/hazel"),
            Map.entry("hemlock", "reforestry:block/tree_saplings/hemlock"),
            Map.entry("hill_cherry", "reforestry:block/tree_saplings/hill_cherry"),
            Map.entry("holly", "reforestry:block/tree_saplings/holly"),
            Map.entry("hornbeam", "reforestry:block/tree_saplings/hornbeam"),
            Map.entry("ipe", "reforestry:block/tree_saplings/ipe"),
            Map.entry("iroko", "reforestry:block/tree_saplings/iroko"),
            Map.entry("jacaranda", "reforestry:block/tree_saplings/jacaranda"),
            Map.entry("jungle", "minecraft:block/jungle_sapling"),
            Map.entry("juniper", "reforestry:block/tree_saplings/juniper"),
            Map.entry("kapok", "reforestry:block/tree_saplings/kapok"),
            Map.entry("kauri", "reforestry:block/tree_saplings/kauri"),
            Map.entry("key_lime", "reforestry:block/tree_saplings/key_lime"),
            Map.entry("kumquat", "reforestry:block/tree_saplings/kumquat"),
            Map.entry("larch", "reforestry:block/tree_saplings/larch"),
            Map.entry("lemon", "reforestry:block/tree_saplings/lemon"),
            Map.entry("lime", "reforestry:block/tree_saplings/lime"),
            Map.entry("loblolly_pine", "reforestry:block/tree_saplings/loblolly_pine"),
            Map.entry("locust", "reforestry:block/tree_saplings/locust"),
            Map.entry("logwood", "reforestry:block/tree_saplings/logwood"),
            Map.entry("macrocarpa", "reforestry:block/tree_saplings/macrocarpa"),
            Map.entry("mahoe", "reforestry:block/tree_saplings/mahoe"),
            Map.entry("mahogany", "reforestry:block/tree_saplings/mahogany"),
            Map.entry("manderin", "reforestry:block/tree_saplings/manderin"),
            Map.entry("mango", "reforestry:block/tree_saplings/mango"),
            Map.entry("maple", "reforestry:block/tree_saplings/maple"),
            Map.entry("nectarine", "reforestry:block/tree_saplings/nectarine"),
            Map.entry("nutmeg", "reforestry:block/tree_saplings/nutmeg"),
            Map.entry("oak", "minecraft:block/oak_sapling"),
            Map.entry("old_fustic", "reforestry:block/tree_saplings/old_fustic"),
            Map.entry("olive", "reforestry:block/tree_saplings/olive"),
            Map.entry("orange", "reforestry:block/tree_saplings/orange"),
            Map.entry("orchard_apple", "reforestry:block/tree_saplings/orchard_apple"),
            Map.entry("osange_orange", "reforestry:block/tree_saplings/osange_orange"),
            Map.entry("padauk", "reforestry:block/tree_saplings/padauk"),
            Map.entry("papaya", "reforestry:block/tree_saplings/papaya"),
            Map.entry("peach", "reforestry:block/tree_saplings/peach"),
            Map.entry("pear", "reforestry:block/tree_saplings/pear"),
            Map.entry("pecan", "reforestry:block/tree_saplings/pecan"),
            Map.entry("pewen", "reforestry:block/tree_saplings/pewen"),
            Map.entry("pine", "reforestry:block/tree_saplings/pine"),
            Map.entry("pink_ivory", "reforestry:block/tree_saplings/pink_ivory"),
            Map.entry("plantain", "reforestry:block/tree_saplings/plantain"),
            Map.entry("plum", "reforestry:block/tree_saplings/plum"),
            Map.entry("pomelo", "reforestry:block/tree_saplings/pomelo"),
            Map.entry("poplar", "reforestry:block/tree_saplings/poplar"),
            Map.entry("prairie_crabapple", "reforestry:block/tree_saplings/prairie_crabapple"),
            Map.entry("purpleheart", "reforestry:block/tree_saplings/purpleheart"),
            Map.entry("rainbow_gum", "reforestry:block/tree_saplings/rainbow_gum"),
            Map.entry("raspberry", "reforestry:block/tree_saplings/raspberry"),
            Map.entry("red_banana", "reforestry:block/tree_saplings/red_banana"),
            Map.entry("red_maple", "reforestry:block/tree_saplings/red_maple"),
            Map.entry("redcurrant", "reforestry:block/tree_saplings/redcurrant"),
            Map.entry("rose_gum", "reforestry:block/tree_saplings/rose_gum"),
            Map.entry("rosewood", "reforestry:block/tree_saplings/rosewood"),
            Map.entry("rowan", "reforestry:block/tree_saplings/rowan"),
            Map.entry("sallow", "reforestry:block/tree_saplings/sallow"),
            Map.entry("satsuma", "reforestry:block/tree_saplings/satsuma"),
            Map.entry("sequoia", "reforestry:block/tree_saplings/sequoia"),
            Map.entry("sipiri", "reforestry:block/tree_saplings/sipiri"),
            Map.entry("spruce", "minecraft:block/spruce_sapling"),
            Map.entry("star_anise", "reforestry:block/tree_saplings/star_anise"),
            Map.entry("starfruit", "reforestry:block/tree_saplings/starfruit"),
            Map.entry("swamp_gum", "reforestry:block/tree_saplings/swamp_gum"),
            Map.entry("sweet_crabapple", "reforestry:block/tree_saplings/sweet_crabapple"),
            Map.entry("sweetgum", "reforestry:block/tree_saplings/sweetgum"),
            Map.entry("sycamore", "reforestry:block/tree_saplings/sycamore"),
            Map.entry("tangerine", "reforestry:block/tree_saplings/tangerine"),
            Map.entry("teak", "reforestry:block/tree_saplings/teak"),
            Map.entry("walnut", "reforestry:block/tree_saplings/walnut"),
            Map.entry("wenge", "reforestry:block/tree_saplings/wenge"),
            Map.entry("whitebeam", "reforestry:block/tree_saplings/whitebeam"),
            Map.entry("wild_cherry", "reforestry:block/tree_saplings/wild_cherry"),
            Map.entry("willow", "reforestry:block/tree_saplings/willow"),
            Map.entry("yew", "reforestry:block/tree_saplings/yew"),
            Map.entry("zebrawood", "reforestry:block/tree_saplings/zebrawood")
    );

    private static final String FALLBACK_SPECIES = "oak";

    @Override
    public void resolveBlockStates(Context context) {
        ImmutableMap.Builder<Identifier, Identifier> base = ImmutableMap.builder();
        for (Map.Entry<String, String> entry : SPECIES_TO_MODEL.entrySet()) {
            base.put(ReForestry.id("tree_" + entry.getKey()), Identifier.parse(entry.getValue()));
        }
        Identifier fallback = Identifier.parse(SPECIES_TO_MODEL.get(FALLBACK_SPECIES));

        SpeciesDispatchModel.Unbaked model = new SpeciesDispatchModel.Unbaked(base.build(), Map.of(), fallback, null);
        for (BlockState state : context.block().getStateDefinition().getPossibleStates()) {
            context.setModel(state, model);
        }
    }
}
