#!/usr/bin/env python3
"""Generates assets/<namespace>/items/<id>.json item model definitions.

Minecraft 26.2 requires an item model definition (a JSON file under
assets/<namespace>/items/, separate from the older models/item/<id>.json)
for every item to render. ForestryCE's assets predate this system (it ships
for 1.20.1), so every item we port needs one of these generated by hand -
this script does that, optionally with per-layer color tints for items whose
color comes from a fixed RGB value (the "minecraft:constant" tint source),
which is how Forestry's comb/pollen colors are ported now that the old
Forge ItemColor Java API has been replaced by this data-driven system.

Usage:
  python3 tools/generate_item_model_definitions.py --root . --namespace reforestry --apply
  python3 tools/generate_item_model_definitions.py --root . --namespace reforestry --tints tints.json --apply

tints.json maps item id -> list of 0xRRGGBB ints (0, 1, or 2 entries, one
per model layer). An empty/absent list means no tints array is written
(the item just uses its texture as painted). Example:
  {
    "honey_drop": [],
    "pollen_cluster_normal": [10617381, 10617381],
    "bee_comb_honey": [15252842, 16744491]
  }

Without --tints this scans models/item/*.json and writes missing items/*.json
(so every id has a 26.2 item definition). Existing items/*.json are left alone.

Without --apply this only prints what would be written (dry run).
"""
import argparse
import json
import sys
from pathlib import Path


def to_signed_argb(rgb: int) -> int:
    argb = 0xFF000000 | (rgb & 0xFFFFFF)
    return argb - 0x100000000 if argb >= 0x80000000 else argb


def build_definition(namespace: str, item_id: str, tint_colors):
    model = {
        "type": "minecraft:model",
        "model": f"{namespace}:item/{item_id}",
    }
    if tint_colors:
        model["tints"] = [
            {"type": "minecraft:constant", "value": to_signed_argb(rgb)}
            for rgb in tint_colors
        ]
    return {"model": model}


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", default=".", help="project root (default: current directory)")
    parser.add_argument("--namespace", required=True, help="resource namespace, e.g. reforestry")
    parser.add_argument("--tints", help="optional JSON file mapping item id -> [0xRRGGBB, ...]; omit to fill missing items from models/item")
    parser.add_argument("--apply", action="store_true", help="write files (default: dry run)")
    args = parser.parse_args()

    assets = Path(args.root) / "src" / "main" / "resources" / "assets" / args.namespace
    items_dir = assets / "items"
    models_item = assets / "models" / "item"
    if args.tints:
        tints_map = json.loads(Path(args.tints).read_text(encoding="utf-8"))
        item_ids = list(tints_map.keys())
        overwrite = True
    else:
        tints_map = {}
        item_ids = sorted(path.stem for path in models_item.glob("*.json"))
        overwrite = False

    mode = "APPLY" if args.apply else "DRY RUN"
    print(f"[{mode}] writing item model definitions under {items_dir}\n")

    if args.apply:
        items_dir.mkdir(parents=True, exist_ok=True)

    written = 0
    skipped = 0
    for item_id in item_ids:
        path = items_dir / f"{item_id}.json"
        if path.exists() and not overwrite:
            skipped += 1
            continue
        tint_colors = tints_map.get(item_id, [])
        definition = build_definition(args.namespace, item_id, tint_colors)
        text = json.dumps(definition, indent=2) + "\n"
        tint_note = f" (tints: {[hex(c) for c in tint_colors]})" if tint_colors else ""
        print(f"{path.relative_to(Path(args.root))}{tint_note}")
        if args.apply:
            path.write_text(text, encoding="utf-8")
        written += 1

    print(f"\n{written} file(s) {'written' if args.apply else 'would be written'}"
          + (f", {skipped} existing skipped" if skipped else ""))
    if not args.apply:
        print("dry run only - rerun with --apply to write files")


if __name__ == "__main__":
    main()
